- name: install dnf install python36 gcc python3-devel -y
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - python36 
  - gcc 
  - python3-devel  

- name: appsetup
  import_role:  
    name: common
    tasks_from: app-setup

- name:   
  ansible.builtin.command: pip3.6 install -r requirements.txt   
  args:
    chdir: /app    

- name: systemd setup
  import_role:
    name: common
    tasks_from: systemd    
