- name:
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name:
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name:
  dnf:
    name: rabbitmq-server
    state: present
- name:
  service:
    name: rabbitmq-server 
    state: started
    enabled: yes


- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_user', region='us-east-1', decrypt=True ) }}"
    password: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_password', region='us-east-1', decrypt=True ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# - name:
#   command: rabbitmqctl add_user roboshop roboshop123
# - name:
#   command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"