- name: diable mysql
  command: dnf module disable mysql -y

- name:
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

  # - name:
  #   command: dnf install mysql-community-server -y

- name:
  dnf:
    name: mysql-community-server
    state: present

- name:
  service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  command: mysql_secure_installation --set-root-pass RoboShop@1    
