- name:
  import_role:
    name: common
    tasks_from: app-setup
  tags:
  - app-setup  

- name: mongodb setup
  import_role:
    name: common
    tasks_from: mongodb-setup 

- name: js
  import_role:
    name: common
    tasks_from: nodejs   

- name: sys
  import_role:
    name:  common
    tasks_from: systemd