- name: 
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: 
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
- name: 
  ansible.builtin.command: rm -rf /usr/share/nginx/html/*
- name: 
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp/web.zip
- name: 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: 
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

    
- name: 
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 
  notify:
  - Restart nginx

