

- name: add user
  ansible.builtin.user:
    name: roboshop

- name: setup an app directory
  ansible.builtin.file:
    path: /app
    state: absent


- name: setup an app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download the {{component}} code to created app directory"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "unzipping {{component}}"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes